//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyHunkGym
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Blog
    {

        public int blog_id { get; set; }
        
        [Display(Name ="Blog Heading")]       
        public string blog_heading { get; set; }

        [Display(Name = "Blog Text")]
        public string blog_text { get; set; }
        
        [Display(Name = "Blog Image")]
        public string blog_img { get; set; }
        
        [Display(Name = "Blog Owner")]
        public string blog_owner { get; set; }
    }
}
